services:
  frontend:
    image: kraarush/opportunex-frontend
    env_file:
      - ./Frontend/.env  
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: kraarush/opportunex-backend
    env_file:
      - ./Backend/.env
    ports:
      - "3000:3000"


# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     image: kraarush/opportunex-frontend
#     env_file:
#       - ./frontend/.en
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     image: kraarush/opportunex-backend
#     env_file:
#       - ./backend/.env
#     ports:
#       - "3000:3000"




# Frontend
# FROM node:20.18.0-alpine
# WORKDIR /frontend
# COPY package*.json ./
# RUN npm install --production
# COPY . .
# RUN npm run build
# FROM nginx:latest
# COPY --from=0 /frontend/dist /usr/share/nginx/html
# EXPOSE 5173
# CMD ["nginx", "-g", "daemon off;"]



# Backend
# FROM node:20.18.0-alpine
# WORKDIR /backend
# COPY package*.json ./
# RUN npm install --only=production
# COPY . .
# EXPOSE 3000
# CMD ["npm", "run", "start"]   