services:
  frontend:
    build: ./Frontend 
    env_file:
      - ./Frontend/.env  
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env  
